### ISSUE TITLE
ComboBox selection will freeze UI

### ISSUE THREAD

**Issue by th0masj0** [omikhailov/handyvalidation#1]
Hey,

I recognized freezing UI using your lib together with a ComboBox. Can you please provide a working sample?

```
....
    public IList<string> Items = new List<string>(){"A", "B", "C"};
    public Property<string> SelectedItem = new()
    {
        Validator = new RulesValidator<string>(
            Rule.NotNull().WithMessage("Select Item"))
    };
....
            <StackPanel Margin="0,0,0,16">
                <ComboBox
                    HorizontalAlignment="Stretch"
                    Header="Selectable"
                    ItemsSource="{x:Bind ViewModel.Items}"
                    SelectedItem="{x:Bind ViewModel.SelectedItem.Value, Mode=TwoWay}"
                    PlaceholderText="Please select a item ..." />
                <TextBlock
                    Style="{StaticResource ValidationMessage}"
                    Text="{x:Bind ViewModel.SelectedItem.Validator.FirstIssue, Mode=OneWay}"
                    Visibility="{x:Bind ViewModel.SelectedItem.Validator.HasIssues, Mode=OneWay}" />
            </StackPanel>
....
```

Regards Thomas

**Comment by omikhailov** [comment]
@thomasjoscht Thank you for reporting this issue, I just published package v1.0.10, please update references to get a fix.

The problem was that ComboBox sets the value twice, and by default Property was not checking the assigned values for equality. Because Property sets the value asynchronously, PropertyChanged events looked for ComboBox like they were unrelated to each other, and it couldn't track and stop recursive calls. Equality checks will now be enabled by default.
